const RESTAURANT = {
  name: 'RestaurantOS Demo Restaurant',
  location: 'Bengaluru, Karnataka',
  address: '42 MG Road, Bengaluru, Karnataka 560001',
  gstNumber: '29AABCR7654M1Z8',
  phone: '+91 80 4567 8900',
  email: 'demo@restaurantos.com',
  businessHours: 'Mon–Sun: 11:00 AM – 11:00 PM',
};

const MENU_CATEGORIES = [
  { name: 'Starters', description: 'Appetizers and small plates', sortOrder: 1 },
  { name: 'Soups', description: 'Hot and cold soups', sortOrder: 2 },
  { name: 'Salads', description: 'Fresh garden salads', sortOrder: 3 },
  { name: 'Main Course', description: 'Hearty main dishes', sortOrder: 4 },
  { name: 'Indian', description: 'Authentic Indian cuisine', sortOrder: 5 },
  { name: 'Chinese', description: 'Indo-Chinese favourites', sortOrder: 6 },
  { name: 'Italian', description: 'Pastas and pizzas', sortOrder: 7 },
  { name: 'Beverages', description: 'Drinks and refreshments', sortOrder: 8 },
  { name: 'Desserts', description: 'Sweet treats', sortOrder: 9 },
  { name: 'Combos', description: 'Value meal combos', sortOrder: 10 },
];

const EXPENSE_CATEGORIES = [
  'Rent', 'Electricity', 'Gas', 'Internet', 'Maintenance',
  'Salary', 'Cleaning', 'Marketing', 'Transportation', 'Office Supplies',
];

const PRODUCT_CATEGORIES = [
  'Dry Goods', 'Dairy Products', 'Meat & Poultry', 'Seafood',
  'Spices & Condiments', 'Beverages Stock', 'Packaging', 'Cleaning Supplies',
  'Frozen Foods', 'Fresh Produce',
];

const WAREHOUSES = [
  { name: 'Main Warehouse', location: 'Basement, MG Road outlet' },
  { name: 'Cold Storage', location: 'Refrigerated unit — Level B1' },
  { name: 'Dry Storage', location: 'Dry goods room — Level B1' },
  { name: 'Kitchen Store', location: 'Active kitchen pantry' },
];

const INGREDIENT_BASES = [
  'Basmati Rice', 'Jasmine Rice', 'Chicken Breast', 'Chicken Thigh', 'Chicken Wings',
  'Mutton', 'Lamb Mince', 'Paneer', 'Tofu', 'Prawns', 'Fish Fillet', 'Calamari',
  'Tomatoes', 'Onions', 'Potatoes', 'Carrots', 'Capsicum', 'Broccoli', 'Spinach',
  'Mushrooms', 'Garlic', 'Ginger', 'Green Chillies', 'Coriander', 'Mint', 'Lemon',
  'Butter', 'Fresh Cream', 'Milk', 'Yogurt', 'Cheese', 'Mozzarella', 'Parmesan',
  'Flour', 'Cornflour', 'Bread Crumbs', 'Pasta', 'Pizza Dough', 'Noodles',
  'Cooking Oil', 'Olive Oil', 'Ghee', 'Sugar', 'Salt', 'Black Pepper',
  'Turmeric', 'Cumin', 'Coriander Powder', 'Garam Masala', 'Red Chilli Powder',
  'Cardamom', 'Cinnamon', 'Cloves', 'Bay Leaves', 'Star Anise', 'Mustard Seeds',
  'Cashews', 'Almonds', 'Raisins', 'Coconut Milk', 'Tamarind', 'Soy Sauce',
  'Vinegar', 'Honey', 'Coffee Beans', 'Tea Leaves', 'Cocoa Powder', 'Vanilla',
  'Ice Cream Base', 'Chocolate', 'Strawberries', 'Mango Pulp', 'Banana',
  'Lettuce', 'Cucumber', 'Bell Pepper Red', 'Bell Pepper Yellow', 'Zucchini',
  'Eggplant', 'Cauliflower', 'Cabbage', 'Beans', 'Peas', 'Corn Kernels',
  'Chickpeas', 'Black Lentils', 'Kidney Beans', 'Coconut', 'Peanuts',
  'Sesame Seeds', 'Spring Onions', 'Celery', 'Basil', 'Oregano', 'Thyme',
  'Rosemary', 'Parsley', 'Paprika', 'Oregano Dried', 'Baking Powder',
  'Baking Soda', 'Yeast', 'Rice Vinegar', 'Fish Sauce', 'Oyster Sauce',
  'Tomato Paste', 'Tomato Puree', 'Chicken Stock', 'Vegetable Stock', 'Beef Stock',
  'Worcestershire Sauce', 'Tabasco', 'Mayonnaise', 'Ketchup', 'Mustard',
  'Tortilla Wraps', 'Burger Buns', 'Pav Buns', 'Naan Dough Mix', 'Papad',
  'Saffron', 'Fenugreek', 'Asafoetida', 'Dry Mango Powder', 'Pomegranate Seeds',
  'Walnuts', 'Pistachios', 'Dates', 'Jaggery', 'Condensed Milk', 'Evaporated Milk',
  'Whipped Cream', 'Mascarpone', 'Ricotta', 'Feta Cheese', 'Blue Cheese',
  'Smoked Salmon', 'Bacon', 'Sausage', 'Ham', 'Salami', 'Prosciutto',
  'Quinoa', 'Bulgur', 'Couscous', 'Polenta', 'Semolina', 'Rice Paper',
  'Wonton Wrappers', 'Tempura Batter', 'Breadcrumbs Japanese', 'Panko',
  'Matcha Powder', 'Chai Masala', 'Rose Water', 'Kewra Water', 'Screw Pine',
  'Edamame', 'Tofu Silken', 'Tempeh', 'Seaweed', 'Wasabi', 'Pickled Ginger',
  'Kimchi Base', 'Sriracha', 'Hoisin Sauce', 'Teriyaki Sauce', 'Miso Paste',
  'Tahini', 'Hummus Base', 'Falafel Mix', 'Pita Bread Mix', 'Taco Shells',
];

const MENU_ITEMS = [
  { name: 'Butter Chicken', category: 'Indian', price: 349, prep: 25, desc: 'Creamy tomato curry with tender tandoori chicken' },
  { name: 'Paneer Butter Masala', category: 'Indian', price: 279, prep: 20, desc: 'Rich cottage cheese in buttery tomato gravy' },
  { name: 'Chicken Biryani', category: 'Indian', price: 299, prep: 30, desc: 'Fragrant dum biryani with marinated chicken' },
  { name: 'Veg Biryani', category: 'Indian', price: 249, prep: 28, desc: 'Aromatic basmati rice with seasonal vegetables' },
  { name: 'Dal Makhani', category: 'Indian', price: 199, prep: 22, desc: 'Slow-cooked black lentils with cream and butter' },
  { name: 'Palak Paneer', category: 'Indian', price: 259, prep: 18, desc: 'Cottage cheese cubes in spiced spinach gravy' },
  { name: 'Tandoori Chicken', category: 'Indian', price: 329, prep: 30, desc: 'Char-grilled chicken marinated in yogurt and spices' },
  { name: 'Malai Kofta', category: 'Indian', price: 269, prep: 22, desc: 'Fried vegetable dumplings in creamy sauce' },
  { name: 'Chole Bhature', category: 'Indian', price: 189, prep: 20, desc: 'Spiced chickpeas with fluffy fried bread' },
  { name: 'Masala Dosa', category: 'Indian', price: 149, prep: 15, desc: 'Crispy rice crepe with spiced potato filling' },
  { name: 'Paneer Tikka', category: 'Starters', price: 249, prep: 15, desc: 'Grilled paneer cubes with mint chutney' },
  { name: 'Chicken Tikka', category: 'Starters', price: 279, prep: 18, desc: 'Smoky tandoori chicken skewers' },
  { name: 'Samosa', category: 'Starters', price: 49, prep: 10, desc: 'Crispy pastry with spiced potato filling' },
  { name: 'Spring Rolls', category: 'Starters', price: 149, prep: 12, desc: 'Crispy vegetable spring rolls with dip' },
  { name: 'Fish Amritsari', category: 'Starters', price: 299, prep: 16, desc: 'Batter-fried fish with ajwain spices' },
  { name: 'Hara Bhara Kebab', category: 'Starters', price: 199, prep: 14, desc: 'Green pea and spinach patties' },
  { name: 'Tom Yum Soup', category: 'Soups', price: 179, prep: 12, desc: 'Spicy Thai-style soup with lemongrass' },
  { name: 'Manchow Soup', category: 'Soups', price: 149, prep: 10, desc: 'Indo-Chinese thick soup with crispy noodles' },
  { name: 'Sweet Corn Soup', category: 'Soups', price: 129, prep: 10, desc: 'Classic creamy sweet corn soup' },
  { name: 'Hot & Sour Soup', category: 'Soups', price: 139, prep: 10, desc: 'Tangy soup with vegetables and tofu' },
  { name: 'Caesar Salad', category: 'Salads', price: 219, prep: 8, desc: 'Romaine lettuce with parmesan and croutons' },
  { name: 'Greek Salad', category: 'Salads', price: 199, prep: 8, desc: 'Fresh vegetables with feta and olives' },
  { name: 'Kachumber Salad', category: 'Salads', price: 99, prep: 5, desc: 'Indian chopped salad with lemon dressing' },
  { name: 'Grilled Chicken Steak', category: 'Main Course', price: 399, prep: 25, desc: 'Herb-marinated grilled chicken with sides' },
  { name: 'Lamb Rogan Josh', category: 'Main Course', price: 449, prep: 35, desc: 'Kashmiri slow-cooked lamb curry' },
  { name: 'Fish Curry', category: 'Main Course', price: 379, prep: 22, desc: 'Coastal coconut fish curry' },
  { name: 'Veg Hakka Noodles', category: 'Chinese', price: 199, prep: 12, desc: 'Stir-fried noodles with vegetables' },
  { name: 'Chicken Fried Rice', category: 'Chinese', price: 229, prep: 14, desc: 'Wok-tossed rice with chicken and egg' },
  { name: 'Chilli Chicken', category: 'Chinese', price: 269, prep: 16, desc: 'Crispy chicken in spicy Indo-Chinese sauce' },
  { name: 'Manchurian Gravy', category: 'Chinese', price: 219, prep: 14, desc: 'Vegetable balls in tangy Manchurian sauce' },
  { name: 'Kung Pao Chicken', category: 'Chinese', price: 289, prep: 16, desc: 'Stir-fried chicken with peanuts and chillies' },
  { name: 'Dim Sum Platter', category: 'Chinese', price: 349, prep: 18, desc: 'Assorted steamed dumplings' },
  { name: 'Margherita Pizza', category: 'Italian', price: 299, prep: 18, desc: 'Classic tomato, mozzarella and basil pizza' },
  { name: 'Pasta Alfredo', category: 'Italian', price: 279, prep: 16, desc: 'Creamy fettuccine with parmesan sauce' },
  { name: 'Penne Arrabiata', category: 'Italian', price: 259, prep: 14, desc: 'Penne in spicy tomato sauce' },
  { name: 'Mushroom Risotto', category: 'Italian', price: 319, prep: 22, desc: 'Creamy arborio rice with wild mushrooms' },
  { name: 'Lasagna', category: 'Italian', price: 349, prep: 25, desc: 'Layered pasta with meat sauce and cheese' },
  { name: 'Cold Coffee', category: 'Beverages', price: 99, prep: 5, desc: 'Chilled blended coffee with ice cream' },
  { name: 'Mojito', category: 'Beverages', price: 149, prep: 5, desc: 'Mint lime mocktail with soda' },
  { name: 'Mango Lassi', category: 'Beverages', price: 79, prep: 4, desc: 'Traditional yogurt mango drink' },
  { name: 'Fresh Lime Soda', category: 'Beverages', price: 59, prep: 3, desc: 'Sweet or salted lime soda' },
  { name: 'Masala Chai', category: 'Beverages', price: 49, prep: 5, desc: 'Spiced Indian tea with milk' },
  { name: 'Iced Tea', category: 'Beverages', price: 69, prep: 3, desc: 'Peach flavoured iced tea' },
  { name: 'Chocolate Brownie', category: 'Desserts', price: 129, prep: 5, desc: 'Warm brownie with vanilla ice cream' },
  { name: 'Gulab Jamun', category: 'Desserts', price: 89, prep: 5, desc: 'Milk dumplings in rose-scented syrup' },
  { name: 'Ice Cream Sundae', category: 'Desserts', price: 149, prep: 5, desc: 'Three scoops with chocolate sauce and nuts' },
  { name: 'Rasmalai', category: 'Desserts', price: 99, prep: 5, desc: 'Soft cottage cheese discs in saffron milk' },
  { name: 'Tiramisu', category: 'Desserts', price: 179, prep: 5, desc: 'Classic Italian coffee-soaked dessert' },
  { name: 'Family Thali', category: 'Combos', price: 899, prep: 30, desc: 'Complete meal for four with variety of dishes' },
  { name: 'Lunch Combo', category: 'Combos', price: 249, prep: 15, desc: 'Main, rice, dal, roti and dessert' },
  { name: 'Burger Combo', category: 'Combos', price: 299, prep: 12, desc: 'Chicken burger with fries and drink' },
  { name: 'Pizza & Pasta Combo', category: 'Combos', price: 449, prep: 20, desc: 'Personal pizza with half pasta portion' },
  { name: 'Tandoori Roti', category: 'Indian', price: 25, prep: 8, desc: 'Whole wheat flatbread from tandoor' },
  { name: 'Butter Naan', category: 'Indian', price: 45, prep: 8, desc: 'Soft leavened bread brushed with butter' },
  { name: 'Garlic Naan', category: 'Indian', price: 55, prep: 8, desc: 'Naan topped with fresh garlic and coriander' },
  { name: 'Jeera Rice', category: 'Indian', price: 129, prep: 12, desc: 'Basmati rice tempered with cumin seeds' },
  { name: 'Prawn Curry', category: 'Main Course', price: 449, prep: 20, desc: 'Coastal prawn curry with coconut milk' },
  { name: 'Egg Curry', category: 'Main Course', price: 179, prep: 15, desc: 'Boiled eggs in spiced onion-tomato gravy' },
  { name: 'Veg Pulao', category: 'Main Course', price: 189, prep: 18, desc: 'Fragrant rice with mixed vegetables' },
  { name: 'Chicken Wrap', category: 'Main Course', price: 199, prep: 10, desc: 'Grilled chicken wrap with salad and sauce' },
  { name: 'Club Sandwich', category: 'Main Course', price: 219, prep: 10, desc: 'Triple-decker sandwich with fries' },
  { name: 'Prawn Fried Rice', category: 'Chinese', price: 279, prep: 14, desc: 'Wok-fried rice with prawns and vegetables' },
  { name: 'Schezwan Fried Rice', category: 'Chinese', price: 219, prep: 12, desc: 'Spicy Schezwan sauce fried rice' },
  { name: 'BBQ Chicken Pizza', category: 'Italian', price: 349, prep: 18, desc: 'Pizza with BBQ chicken and onions' },
  { name: 'Four Cheese Pizza', category: 'Italian', price: 379, prep: 18, desc: 'Mozzarella, parmesan, gorgonzola and ricotta' },
  { name: 'Affogato', category: 'Desserts', price: 119, prep: 3, desc: 'Espresso poured over vanilla gelato' },
  { name: 'Cheesecake', category: 'Desserts', price: 159, prep: 5, desc: 'New York style baked cheesecake slice' },
  { name: 'Filter Coffee', category: 'Beverages', price: 45, prep: 5, desc: 'South Indian filter kaapi' },
  { name: 'Virgin Piña Colada', category: 'Beverages', price: 139, prep: 5, desc: 'Pineapple coconut mocktail' },
  { name: 'Paneer Kathi Roll', category: 'Starters', price: 169, prep: 10, desc: 'Paneer wrapped in paratha with chutney' },
  { name: 'Crispy Corn', category: 'Starters', price: 159, prep: 10, desc: 'Deep-fried corn with spicy seasoning' },
  { name: 'Prawn Tempura', category: 'Starters', price: 329, prep: 14, desc: 'Light battered prawns with dipping sauce' },
  { name: 'Minestrone Soup', category: 'Soups', price: 159, prep: 12, desc: 'Italian vegetable soup with pasta' },
  { name: 'Chef Special Thali', category: 'Combos', price: 499, prep: 35, desc: 'Daily chef-curated complete thali' },
  { name: 'Kids Meal', category: 'Combos', price: 199, prep: 10, desc: 'Mini burger, fries and juice for children' },
  { name: 'Date Night Platter', category: 'Combos', price: 1299, prep: 40, desc: 'Premium starters and mains for two' },
  { name: 'Office Lunch Box', category: 'Combos', price: 179, prep: 12, desc: 'Compact lunch box with roti, sabzi and rice' },
  { name: 'Weekend Brunch', category: 'Combos', price: 599, prep: 25, desc: 'Brunch spread with eggs, pancakes and juice' },
  { name: 'Raita', category: 'Indian', price: 59, prep: 5, desc: 'Cooling yogurt side with cucumber' },
  { name: 'Papad', category: 'Starters', price: 29, prep: 3, desc: 'Crispy roasted papad with pickles' },
  { name: 'Mixed Pickle', category: 'Starters', price: 39, prep: 2, desc: 'Assorted Indian achaar' },
  { name: 'Coconut Rice', category: 'Indian', price: 149, prep: 14, desc: 'South Indian coconut flavoured rice' },
  { name: 'Medu Vada', category: 'Starters', price: 89, prep: 12, desc: 'Crispy lentil doughnuts with chutney' },
  { name: 'Idli Sambar', category: 'Indian', price: 99, prep: 10, desc: 'Steamed rice cakes with lentil stew' },
  { name: 'Pav Bhaji', category: 'Indian', price: 129, prep: 15, desc: 'Spiced vegetable mash with buttered pav' },
];

const FIRST_NAMES = [
  'Raj', 'Priya', 'Amit', 'Sneha', 'Vikram', 'Ananya', 'Rahul', 'Kavya',
  'Arjun', 'Divya', 'Sanjay', 'Meera', 'Karan', 'Pooja', 'Rohan', 'Neha',
  'Aditya', 'Shreya', 'Nikhil', 'Isha', 'Varun', 'Tanvi', 'Harsh', 'Riya',
];

const LAST_NAMES = [
  'Sharma', 'Patel', 'Kumar', 'Reddy', 'Singh', 'Gupta', 'Iyer', 'Nair',
  'Menon', 'Joshi', 'Desai', 'Rao', 'Verma', 'Malhotra', 'Chopra', 'Bhat',
];

const SUPPLIER_NAMES = [
  'Fresh Farms Karnataka', 'Metro Dairy Bengaluru', 'Spice World India', 'Ocean Catch Seafood',
  'Golden Grain Traders', 'Premium Poultry Farms', 'Green Valley Produce', 'Royal Basmati Co',
  'City Beverages Distributors', 'PackRight Solutions', 'CleanPro Hospitality', 'Frozen Foods Express',
  'Artisan Cheese Imports', 'Organic Harvest Co-op', 'Masala Mahal Wholesale', 'Baker Street Supplies',
  'Tea & Coffee Merchants', 'Wine & Spirits Karnataka', 'Eco Packaging Ltd', 'Kitchen Equipment Hub',
  'Fresh Herbs Garden', 'Dairy Delights Pvt Ltd', 'Meat Masters Bengaluru', 'Seafood Supreme',
  'Global Gourmet Imports', 'Sunrise Vegetables', 'Himalayan Spices', 'Urban Frozen Foods',
  'Quality Oils & Fats', 'Restaurant Depot India',
];

module.exports = {
  RESTAURANT,
  MENU_CATEGORIES,
  EXPENSE_CATEGORIES,
  PRODUCT_CATEGORIES,
  WAREHOUSES,
  INGREDIENT_BASES,
  MENU_ITEMS,
  FIRST_NAMES,
  LAST_NAMES,
  SUPPLIER_NAMES,
};
